# Multiple notifications bug: https://github.com/argoproj-labs/argocd-notifications/issues/90
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    myUsername: "Jane Doe" # ADD HERE YOUR USERNAME
  service.webhook.webhook-site: |
    url: "https://webhook.site/70a7b081-ea61-4611-b424-542f2b3f6cc4"
    headers:
    - name: Content-Type
      value: application/json
  template.app-sync-succeeded: |
    webhook:
      webhook-site:
        method: POST
        body: |
          {
            "message": "Congrats {{.context.myUsername}}! You synced you application successfully!"
          }
